POST http://localhost:8000/api/user HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9sb2dpbiIsImlhdCI6MTYzODQ1ODgzMiwiZXhwIjoxNjM4NDYyNDMyLCJuYmYiOjE2Mzg0NTg4MzIsImp0aSI6Ims2a1BEekVxclhLeHZoYlgiLCJzdWIiOjEyLCJwcnYiOiI3Y2M5MzZkYjZjOTZkM2Q5MDQ2Nzk4OTNkNDM3OGZjYmM3NmUyMTFmIn0.lby7h_VduKXBrxNj5_MwJE2RsveIOvPF0LtMJO31Zs8

{
    "email" : "randommail@mail.com",
    "password" : "strongkey123"

}