POST http://localhost:8000/api/users HTTP/1.1
content-type: application/json

{
    "name": "ricardo garces",
    "email" : "randommail@mail.com",
    "password" : "strongkey123",
    "password_confirmation": "strongkey123"
}

###

POST http://localhost:8000/api/login HTTP/1.1
content-type: application/json

{
    "email" : "randommail@mail.com",
    "password" : "strongkey123"
}

##